### ISSUE TITLE
Request: binary release on github

### ISSUE THREAD

**Issue by m040601** [MarioJim/fuzzy-pdf#2]
Very interesting project .
Came here after finding fast-p, which seems abandoned.

Nice to know you're an Arch user also and provide a package to compile from source.

I haven't yet tried out, but I'm eager to.
Would it be possible to release it as a binary ? At least compiled for x86_64 ?
This would also make it easier to provied an AUR package fuzzy-pdf-bin.

It would make much easier for people who dont have / dont want to download the 500 mega rust distribution just to quickly try it out.

Perhaps you can also have a look at how other cli rust tools do it, for example,

skim, https://github.com/lotabout/skim/releases
fd, https://github.com/sharkdp/fd

I assume you are aware of github actions right ?
Have a look at how ripgrep, https://github.com/BurntSushi/ripgrep does it, https://github.com/BurntSushi/ripgrep/tree/master/.github/workflows

Thanks in advance

**Comment by MarioJim** [comment]
Hi, thanks for taking a look at my program!

I really like the idea since my program is very dependency-heavy. I'll try to implement it this week, but of course, PRs are welcome. And yeah, my release pipeline would be based on ripgrep's but simpler and without the cross-compilation targets.

**Comment by MarioJim** [comment]
Finally got around to doing this, [fuzzy-pdf-bin](https://aur.archlinux.org/packages/fuzzy-pdf-bin/) package now exists!
